# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedplot',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 18, 9, 45, 26, 21747)),
            preserve_default=False,
        ),
    ]
